# Generated by Django 2.0.4 on 2018-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planner', '0002_auto_20181016_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientitem',
            name='amount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='recipeingredientitem',
            name='denomination',
            field=models.CharField(choices=[('tsp', 'teaspoon'), (('tbsp',), 'tablespoon'), ('g', 'gram'), ('cup', 'cup'), ('qt', 'quart'), ('oz', 'ounce'), ('lb', 'pound'), ('ct', 'ct')], default='ct', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipeingredientitem',
            name='other_instructions',
            field=models.TextField(null=True),
        ),
    ]
