# Generated by Django 2.0.4 on 2018-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planner', '0003_auto_20181121_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientitem',
            name='denomination',
            field=models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('g', 'gram'), ('cup', 'cup'), ('qt', 'quart'), ('oz', 'ounce'), ('lb', 'pound'), ('ct', 'ct')], default='ct', max_length=5),
        ),
    ]
